export type Tag =
  | "announcement"
  | "announce_distribution"
  | "announce_first_case"
  | "announce_order"
  | "announce_support"
  | "announce_free_help"
  | "announce_treatment"
  | "mask"
  | "virus"